# Create a Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cannalogs-pv-volume1
  namespace: cannalogs
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - hard
    # Mount using NFS v 4.1
    - nfsvers=4.1
  nfs:
    # The path in the NAS
    path: "/path/to/folder"
    # The NAS IP
    server: <NFS Server IP>
    # Make sure to allow to write
    readOnly: false

---

# Create a Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cannalogs-pv-volume2
  namespace: cannalogs
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
  mountOptions:
    - hard
    # Mount using NFS v 4.1
    - nfsvers=4.1
  nfs:
    # The path in the NAS
    path: "/path/to/folder"
    # The NAS IP
    server: <NFS Server IP>
    # Make sure to allow to write
    readOnly: false